<?php

/**
 * @file
 * Contains no_views_php.module.
 */
use Drupal\views\ViewExecutable;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function no_views_php_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the no_views_php module.
    case 'help.page.no_views_php':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom views field to include PHP logic in views.') . '</p>';
      return $output;

    default:
  }
}

/*function no_views_php_views_post_render(ViewExecutable $view) {
  if($view->id() == 'estadio' && $view->current_display == 'etapa'){
    dump($view->getHandler('etapa','field', 'pe_views_field'));
    foreach ($view->result as $key => $value) {
      //dump($value);
      //dump($value->_entity->get('pe_views_field')->value);
    }
  }
}
*/